// AgentPaaS Trigger API
//
// The TriggerService handles agent invocation and run lifecycle management.
// Agents are invoked via Invoke or InvokeStream, and runs can be queried,
// listed, or cancelled.
//
// Idempotency Semantics:
//
// Invoke and InvokeStream are idempotent when an idempotency_key is provided:
//
//  1. Same idempotency_key + same payload hash → returns the original Run
//     (safe retry; no duplicate execution).
//  2. Same idempotency_key + different payload → returns ALREADY_EXISTS (409)
//     (conflict; the caller must use a fresh key for a different payload).
//  3. Different idempotency_key (or empty) → a new run is created every time.
//
// Error Conventions (via google.rpc.Status):
//
//  - NOT_FOUND (404):       The requested run_id does not exist.
//  - ALREADY_EXISTS (409):  Idempotency key conflict with a different payload.
//  - FAILED_PRECONDITION (412): Invalid state transition (e.g. cancelling a
//                               completed run).
//  - RESOURCE_EXHAUSTED (8): Budget exceeded for the agent/project.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trigger/v1/trigger.proto

package triggerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunStatus represents the lifecycle state of an agent run.
type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED     RunStatus = 0
	RunStatus_RUN_STATUS_PENDING         RunStatus = 1
	RunStatus_RUN_STATUS_RUNNING         RunStatus = 2
	RunStatus_RUN_STATUS_SUCCEEDED       RunStatus = 3
	RunStatus_RUN_STATUS_FAILED          RunStatus = 4
	RunStatus_RUN_STATUS_CANCELLED       RunStatus = 5
	RunStatus_RUN_STATUS_BUDGET_EXCEEDED RunStatus = 6
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_PENDING",
		2: "RUN_STATUS_RUNNING",
		3: "RUN_STATUS_SUCCEEDED",
		4: "RUN_STATUS_FAILED",
		5: "RUN_STATUS_CANCELLED",
		6: "RUN_STATUS_BUDGET_EXCEEDED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED":     0,
		"RUN_STATUS_PENDING":         1,
		"RUN_STATUS_RUNNING":         2,
		"RUN_STATUS_SUCCEEDED":       3,
		"RUN_STATUS_FAILED":          4,
		"RUN_STATUS_CANCELLED":       5,
		"RUN_STATUS_BUDGET_EXCEEDED": 6,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trigger_v1_trigger_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_trigger_v1_trigger_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{0}
}

// BudgetSummary captures financial and resource usage for a run.
type BudgetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenCount    int64                  `protobuf:"varint,1,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,2,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	WallClockMs   int64                  `protobuf:"varint,3,opt,name=wall_clock_ms,json=wallClockMs,proto3" json:"wall_clock_ms,omitempty"`
	Iterations    int64                  `protobuf:"varint,4,opt,name=iterations,proto3" json:"iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetSummary) Reset() {
	*x = BudgetSummary{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummary) ProtoMessage() {}

func (x *BudgetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummary.ProtoReflect.Descriptor instead.
func (*BudgetSummary) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *BudgetSummary) GetTokenCount() int64 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *BudgetSummary) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *BudgetSummary) GetWallClockMs() int64 {
	if x != nil {
		return x.WallClockMs
	}
	return 0
}

func (x *BudgetSummary) GetIterations() int64 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

// Run represents a single agent execution.
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status        RunStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=agentpaas.trigger.v1.RunStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	BudgetSummary *BudgetSummary         `protobuf:"bytes,9,opt,name=budget_summary,json=budgetSummary,proto3" json:"budget_summary,omitempty"`
	PolicyDigest  string                 `protobuf:"bytes,10,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,11,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Run) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Run) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Run) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Run) GetBudgetSummary() *BudgetSummary {
	if x != nil {
		return x.BudgetSummary
	}
	return nil
}

func (x *Run) GetPolicyDigest() string {
	if x != nil {
		return x.PolicyDigest
	}
	return ""
}

func (x *Run) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

// InvokeRequest triggers an agent run.
//
// Idempotency: see file-level comment above.
type InvokeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentName    string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Payload      []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType  string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// idempotency_key ensures exactly-once semantics when combined with payload
	// hash. See file-level idempotency documentation for details.
	IdempotencyKey string            `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *InvokeRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InvokeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvokeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{4}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListRunsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by agent name.
	AgentName string `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// Optional: filter by run status.
	Status RunStatus `protobuf:"varint,2,opt,name=status,proto3,enum=agentpaas.trigger.v1.RunStatus" json:"status,omitempty"`
	// Maximum number of runs to return. Server may cap this value.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token from a previous ListRunsResponse to request the next page.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{6}
}

func (x *ListRunsRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ListRunsRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *ListRunsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_trigger_v1_trigger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_v1_trigger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_trigger_v1_trigger_proto_rawDescGZIP(), []int{7}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_trigger_v1_trigger_proto protoreflect.FileDescriptor

const file_trigger_v1_trigger_proto_rawDesc = "" +
	"\n" +
	"\x18trigger/v1/trigger.proto\x12\x14agentpaas.trigger.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\"\x8f\x01\n" +
	"\rBudgetSummary\x12\x1f\n" +
	"\vtoken_count\x18\x01 \x01(\x03R\n" +
	"tokenCount\x12\x19\n" +
	"\bcost_usd\x18\x02 \x01(\x01R\acostUsd\x12\"\n" +
	"\rwall_clock_ms\x18\x03 \x01(\x03R\vwallClockMs\x12\x1e\n" +
	"\n" +
	"iterations\x18\x04 \x01(\x03R\n" +
	"iterations\"\xf6\x03\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.agentpaas.trigger.v1.RunStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12J\n" +
	"\x0ebudget_summary\x18\t \x01(\v2#.agentpaas.trigger.v1.BudgetSummaryR\rbudgetSummary\x12#\n" +
	"\rpolicy_digest\x18\n" +
	" \x01(\tR\fpolicyDigest\x12!\n" +
	"\fimage_digest\x18\v \x01(\tR\vimageDigest\"\xc5\x02\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.agentpaas.trigger.v1.InvokeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x0eInvokeResponse\x12+\n" +
	"\x03run\x18\x01 \x01(\v2\x19.agentpaas.trigger.v1.RunR\x03run\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"A\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa5\x01\n" +
	"\x0fListRunsRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.agentpaas.trigger.v1.RunStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"i\n" +
	"\x10ListRunsResponse\x12-\n" +
	"\x04runs\x18\x01 \x03(\v2\x19.agentpaas.trigger.v1.RunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\xc2\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14RUN_STATUS_CANCELLED\x10\x05\x12\x1e\n" +
	"\x1aRUN_STATUS_BUDGET_EXCEEDED\x10\x062\xe7\x04\n" +
	"\x0eTriggerService\x12r\n" +
	"\x06Invoke\x12#.agentpaas.trigger.v1.InvokeRequest\x1a$.agentpaas.trigger.v1.InvokeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/trigger/invoke\x12\x81\x01\n" +
	"\fInvokeStream\x12#.agentpaas.trigger.v1.InvokeRequest\x1a$.agentpaas.trigger.v1.InvokeResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/trigger/invoke/stream0\x01\x12k\n" +
	"\x06GetRun\x12#.agentpaas.trigger.v1.GetRunRequest\x1a\x19.agentpaas.trigger.v1.Run\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/trigger/runs/{run_id}\x12{\n" +
	"\tCancelRun\x12&.agentpaas.trigger.v1.CancelRunRequest\x1a\x19.agentpaas.trigger.v1.Run\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/trigger/runs/{run_id}:cancel\x12s\n" +
	"\bListRuns\x12%.agentpaas.trigger.v1.ListRunsRequest\x1a&.agentpaas.trigger.v1.ListRunsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/trigger/runsB\xd4\x01\n" +
	"\x18com.agentpaas.trigger.v1B\fTriggerProtoP\x01Z8github.com/parvezsyed/agentpaas/api/trigger/v1;triggerv1\xa2\x02\x03ATX\xaa\x02\x14Agentpaas.Trigger.V1\xca\x02\x14Agentpaas\\Trigger\\V1\xe2\x02 Agentpaas\\Trigger\\V1\\GPBMetadata\xea\x02\x16Agentpaas::Trigger::V1b\x06proto3"

var (
	file_trigger_v1_trigger_proto_rawDescOnce sync.Once
	file_trigger_v1_trigger_proto_rawDescData []byte
)

func file_trigger_v1_trigger_proto_rawDescGZIP() []byte {
	file_trigger_v1_trigger_proto_rawDescOnce.Do(func() {
		file_trigger_v1_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trigger_v1_trigger_proto_rawDesc), len(file_trigger_v1_trigger_proto_rawDesc)))
	})
	return file_trigger_v1_trigger_proto_rawDescData
}

var file_trigger_v1_trigger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trigger_v1_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_trigger_v1_trigger_proto_goTypes = []any{
	(RunStatus)(0),                // 0: agentpaas.trigger.v1.RunStatus
	(*BudgetSummary)(nil),         // 1: agentpaas.trigger.v1.BudgetSummary
	(*Run)(nil),                   // 2: agentpaas.trigger.v1.Run
	(*InvokeRequest)(nil),         // 3: agentpaas.trigger.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 4: agentpaas.trigger.v1.InvokeResponse
	(*GetRunRequest)(nil),         // 5: agentpaas.trigger.v1.GetRunRequest
	(*CancelRunRequest)(nil),      // 6: agentpaas.trigger.v1.CancelRunRequest
	(*ListRunsRequest)(nil),       // 7: agentpaas.trigger.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 8: agentpaas.trigger.v1.ListRunsResponse
	nil,                           // 9: agentpaas.trigger.v1.InvokeRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_trigger_v1_trigger_proto_depIdxs = []int32{
	0,  // 0: agentpaas.trigger.v1.Run.status:type_name -> agentpaas.trigger.v1.RunStatus
	10, // 1: agentpaas.trigger.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: agentpaas.trigger.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	10, // 3: agentpaas.trigger.v1.Run.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 4: agentpaas.trigger.v1.Run.budget_summary:type_name -> agentpaas.trigger.v1.BudgetSummary
	9,  // 5: agentpaas.trigger.v1.InvokeRequest.metadata:type_name -> agentpaas.trigger.v1.InvokeRequest.MetadataEntry
	2,  // 6: agentpaas.trigger.v1.InvokeResponse.run:type_name -> agentpaas.trigger.v1.Run
	0,  // 7: agentpaas.trigger.v1.ListRunsRequest.status:type_name -> agentpaas.trigger.v1.RunStatus
	2,  // 8: agentpaas.trigger.v1.ListRunsResponse.runs:type_name -> agentpaas.trigger.v1.Run
	3,  // 9: agentpaas.trigger.v1.TriggerService.Invoke:input_type -> agentpaas.trigger.v1.InvokeRequest
	3,  // 10: agentpaas.trigger.v1.TriggerService.InvokeStream:input_type -> agentpaas.trigger.v1.InvokeRequest
	5,  // 11: agentpaas.trigger.v1.TriggerService.GetRun:input_type -> agentpaas.trigger.v1.GetRunRequest
	6,  // 12: agentpaas.trigger.v1.TriggerService.CancelRun:input_type -> agentpaas.trigger.v1.CancelRunRequest
	7,  // 13: agentpaas.trigger.v1.TriggerService.ListRuns:input_type -> agentpaas.trigger.v1.ListRunsRequest
	4,  // 14: agentpaas.trigger.v1.TriggerService.Invoke:output_type -> agentpaas.trigger.v1.InvokeResponse
	4,  // 15: agentpaas.trigger.v1.TriggerService.InvokeStream:output_type -> agentpaas.trigger.v1.InvokeResponse
	2,  // 16: agentpaas.trigger.v1.TriggerService.GetRun:output_type -> agentpaas.trigger.v1.Run
	2,  // 17: agentpaas.trigger.v1.TriggerService.CancelRun:output_type -> agentpaas.trigger.v1.Run
	8,  // 18: agentpaas.trigger.v1.TriggerService.ListRuns:output_type -> agentpaas.trigger.v1.ListRunsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_trigger_v1_trigger_proto_init() }
func file_trigger_v1_trigger_proto_init() {
	if File_trigger_v1_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trigger_v1_trigger_proto_rawDesc), len(file_trigger_v1_trigger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trigger_v1_trigger_proto_goTypes,
		DependencyIndexes: file_trigger_v1_trigger_proto_depIdxs,
		EnumInfos:         file_trigger_v1_trigger_proto_enumTypes,
		MessageInfos:      file_trigger_v1_trigger_proto_msgTypes,
	}.Build()
	File_trigger_v1_trigger_proto = out.File
	file_trigger_v1_trigger_proto_goTypes = nil
	file_trigger_v1_trigger_proto_depIdxs = nil
}
