// AgentPaaS Trigger API
//
// The TriggerService handles agent invocation and run lifecycle management.
// Agents are invoked via Invoke or InvokeStream, and runs can be queried,
// listed, or cancelled.
//
// Idempotency Semantics:
//
// Invoke and InvokeStream are idempotent when an idempotency_key is provided:
//
//  1. Same idempotency_key + same payload hash → returns the original Run
//     (safe retry; no duplicate execution).
//  2. Same idempotency_key + different payload → returns ALREADY_EXISTS (409)
//     (conflict; the caller must use a fresh key for a different payload).
//  3. Different idempotency_key (or empty) → a new run is created every time.
//
// Error Conventions (via google.rpc.Status):
//
//  - NOT_FOUND (404):       The requested run_id does not exist.
//  - ALREADY_EXISTS (409):  Idempotency key conflict with a different payload.
//  - FAILED_PRECONDITION (412): Invalid state transition (e.g. cancelling a
//                               completed run).
//  - RESOURCE_EXHAUSTED (8): Budget exceeded for the agent/project.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: trigger/v1/trigger.proto

package triggerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TriggerService_Invoke_FullMethodName       = "/agentpaas.trigger.v1.TriggerService/Invoke"
	TriggerService_InvokeStream_FullMethodName = "/agentpaas.trigger.v1.TriggerService/InvokeStream"
	TriggerService_GetRun_FullMethodName       = "/agentpaas.trigger.v1.TriggerService/GetRun"
	TriggerService_CancelRun_FullMethodName    = "/agentpaas.trigger.v1.TriggerService/CancelRun"
	TriggerService_ListRuns_FullMethodName     = "/agentpaas.trigger.v1.TriggerService/ListRuns"
)

// TriggerServiceClient is the client API for TriggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TriggerService manages agent invocation and run lifecycle.
type TriggerServiceClient interface {
	// Invoke triggers a single agent run and returns the Run immediately.
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// InvokeStream triggers an agent run and returns a stream of Run updates
	// via server-sent events (SSE).
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeResponse], error)
	// GetRun retrieves a run by its ID.
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error)
	// CancelRun cancels a pending or running run.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error)
	// ListRuns lists runs with optional filters and pagination.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
}

type triggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTriggerServiceClient(cc grpc.ClientConnInterface) TriggerServiceClient {
	return &triggerServiceClient{cc}
}

func (c *triggerServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, TriggerService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerServiceClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TriggerService_ServiceDesc.Streams[0], TriggerService_InvokeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	first, err := x.Recv()
	if err != nil {
		return nil, err
	}
	return &triggerServiceInvokeStreamClient{ServerStreamingClient: x, first: first}, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TriggerService_InvokeStreamClient = grpc.ServerStreamingClient[InvokeResponse]

type triggerServiceInvokeStreamClient struct {
	grpc.ServerStreamingClient[InvokeResponse]
	first *InvokeResponse
}

func (c *triggerServiceInvokeStreamClient) Recv() (*InvokeResponse, error) {
	if c.first != nil {
		first := c.first
		c.first = nil
		return first, nil
	}
	return c.ServerStreamingClient.Recv()
}

func (c *triggerServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, TriggerService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, TriggerService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, TriggerService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerServiceServer is the server API for TriggerService service.
// All implementations must embed UnimplementedTriggerServiceServer
// for forward compatibility.
//
// TriggerService manages agent invocation and run lifecycle.
type TriggerServiceServer interface {
	// Invoke triggers a single agent run and returns the Run immediately.
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// InvokeStream triggers an agent run and returns a stream of Run updates
	// via server-sent events (SSE).
	InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeResponse]) error
	// GetRun retrieves a run by its ID.
	GetRun(context.Context, *GetRunRequest) (*Run, error)
	// CancelRun cancels a pending or running run.
	CancelRun(context.Context, *CancelRunRequest) (*Run, error)
	// ListRuns lists runs with optional filters and pagination.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	mustEmbedUnimplementedTriggerServiceServer()
}

// UnimplementedTriggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTriggerServiceServer struct{}

func (UnimplementedTriggerServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedTriggerServiceServer) InvokeStream(*InvokeRequest, grpc.ServerStreamingServer[InvokeResponse]) error {
	return status.Error(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedTriggerServiceServer) GetRun(context.Context, *GetRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedTriggerServiceServer) CancelRun(context.Context, *CancelRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedTriggerServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedTriggerServiceServer) mustEmbedUnimplementedTriggerServiceServer() {}
func (UnimplementedTriggerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTriggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriggerServiceServer will
// result in compilation errors.
type UnsafeTriggerServiceServer interface {
	mustEmbedUnimplementedTriggerServiceServer()
}

func RegisterTriggerServiceServer(s grpc.ServiceRegistrar, srv TriggerServiceServer) {
	// If the following call panics, it indicates UnimplementedTriggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TriggerService_ServiceDesc, srv)
}

func _TriggerService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerService_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TriggerServiceServer).InvokeStream(m, &grpc.GenericServerStream[InvokeRequest, InvokeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TriggerService_InvokeStreamServer = grpc.ServerStreamingServer[InvokeResponse]

func _TriggerService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriggerService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TriggerService_ServiceDesc is the grpc.ServiceDesc for TriggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentpaas.trigger.v1.TriggerService",
	HandlerType: (*TriggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _TriggerService_Invoke_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _TriggerService_GetRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _TriggerService_CancelRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _TriggerService_ListRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _TriggerService_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trigger/v1/trigger.proto",
}
