// AgentPaaS Control API
//
// The ControlService provides operational control over agents: packaging,
// running, stopping, policy management, secrets, audit, diagnostics, and
// operator/introspection capabilities.
//
// All RPCs use google.api.http annotations for REST/HTTP mapping.
// Errors follow google.rpc.Status conventions:
//
//  - NOT_FOUND (404)       — requested resource does not exist
//  - ALREADY_EXISTS (409)  — resource or key conflict
//  - FAILED_PRECONDITION (412) — invalid state for the operation
//  - INVALID_ARGUMENT (3)  — malformed request parameters
//  - PERMISSION_DENIED (7) — authorization failure
//  - RESOURCE_EXHAUSTED (8) — budget or quota exceeded
//
// Operator methods (13-18) return structured payloads designed for
// coding-agent clients. CLI/dashboard text is rendered from the same data.
// Each response is self-describing enough for an LLM to act on.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_Pack_FullMethodName                 = "/agentpaas.control.v1.ControlService/Pack"
	ControlService_ExportPreview_FullMethodName        = "/agentpaas.control.v1.ControlService/ExportPreview"
	ControlService_Export_FullMethodName               = "/agentpaas.control.v1.ControlService/Export"
	ControlService_Run_FullMethodName                  = "/agentpaas.control.v1.ControlService/Run"
	ControlService_Stop_FullMethodName                 = "/agentpaas.control.v1.ControlService/Stop"
	ControlService_Logs_FullMethodName                 = "/agentpaas.control.v1.ControlService/Logs"
	ControlService_PolicyApply_FullMethodName          = "/agentpaas.control.v1.ControlService/PolicyApply"
	ControlService_SecretSet_FullMethodName            = "/agentpaas.control.v1.ControlService/SecretSet"
	ControlService_SecretGrant_FullMethodName          = "/agentpaas.control.v1.ControlService/SecretGrant"
	ControlService_SecretRevoke_FullMethodName         = "/agentpaas.control.v1.ControlService/SecretRevoke"
	ControlService_AuditQuery_FullMethodName           = "/agentpaas.control.v1.ControlService/AuditQuery"
	ControlService_AuditExport_FullMethodName          = "/agentpaas.control.v1.ControlService/AuditExport"
	ControlService_Doctor_FullMethodName               = "/agentpaas.control.v1.ControlService/Doctor"
	ControlService_ValidateAgentProject_FullMethodName = "/agentpaas.control.v1.ControlService/ValidateAgentProject"
	ControlService_SummarizeRun_FullMethodName         = "/agentpaas.control.v1.ControlService/SummarizeRun"
	ControlService_ExplainFailure_FullMethodName       = "/agentpaas.control.v1.ControlService/ExplainFailure"
	ControlService_ExplainPolicyDenial_FullMethodName  = "/agentpaas.control.v1.ControlService/ExplainPolicyDenial"
	ControlService_RecommendPolicyPatch_FullMethodName = "/agentpaas.control.v1.ControlService/RecommendPolicyPatch"
	ControlService_GetRunTimeline_FullMethodName       = "/agentpaas.control.v1.ControlService/GetRunTimeline"
	ControlService_NextAction_FullMethodName           = "/agentpaas.control.v1.ControlService/NextAction"
	ControlService_CronAdd_FullMethodName              = "/agentpaas.control.v1.ControlService/CronAdd"
	ControlService_CronList_FullMethodName             = "/agentpaas.control.v1.ControlService/CronList"
	ControlService_CronRemove_FullMethodName           = "/agentpaas.control.v1.ControlService/CronRemove"
	ControlService_ListRuns_FullMethodName             = "/agentpaas.control.v1.ControlService/ListRuns"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlService provides operational control over agent lifecycle, policy,
// secrets, audit logs, and diagnostic/introspection capabilities.
type ControlServiceClient interface {
	// Pack builds an agent image from a project directory.
	Pack(ctx context.Context, in *PackRequest, opts ...grpc.CallOption) (*PackResponse, error)
	// ExportPreview returns the export file manifest after preconditions pass.
	ExportPreview(ctx context.Context, in *ExportPreviewRequest, opts ...grpc.CallOption) (*ExportPreviewResponse, error)
	// Export writes a signed .agentpaas bundle after the secret gate passes.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Run starts a new agent run with the given budget and payload.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Stop terminates a running agent run.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Logs returns a stream of log entries, optionally following in real-time.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// PolicyApply applies or validates an OPA/Rego policy.
	PolicyApply(ctx context.Context, in *PolicyApplyRequest, opts ...grpc.CallOption) (*PolicyApplyResponse, error)
	// SecretSet creates or updates a secret.
	SecretSet(ctx context.Context, in *SecretSetRequest, opts ...grpc.CallOption) (*SecretSetResponse, error)
	// SecretGrant grants a secret to a specific run.
	SecretGrant(ctx context.Context, in *SecretGrantRequest, opts ...grpc.CallOption) (*SecretGrantResponse, error)
	// SecretRevoke revokes a secret from a specific run.
	SecretRevoke(ctx context.Context, in *SecretRevokeRequest, opts ...grpc.CallOption) (*SecretRevokeResponse, error)
	// AuditQuery queries audit log entries with filters and pagination.
	AuditQuery(ctx context.Context, in *AuditQueryRequest, opts ...grpc.CallOption) (*AuditQueryResponse, error)
	// AuditExport exports audit log entries in a specified format.
	AuditExport(ctx context.Context, in *AuditExportRequest, opts ...grpc.CallOption) (*AuditExportResponse, error)
	// Doctor runs system diagnostics and returns health check results.
	Doctor(ctx context.Context, in *DoctorRequest, opts ...grpc.CallOption) (*DoctorResponse, error)
	// ValidateAgentProject validates an agent project directory structure and
	// configuration.
	ValidateAgentProject(ctx context.Context, in *ValidateAgentProjectRequest, opts ...grpc.CallOption) (*ValidateAgentProjectResponse, error)
	// SummarizeRun generates a natural-language summary of a completed run.
	SummarizeRun(ctx context.Context, in *SummarizeRunRequest, opts ...grpc.CallOption) (*SummarizeRunResponse, error)
	// ExplainFailure analyzes a failed run and returns root cause and suggested
	// fixes.
	ExplainFailure(ctx context.Context, in *ExplainFailureRequest, opts ...grpc.CallOption) (*ExplainFailureResponse, error)
	// ExplainPolicyDenial explains why a specific destination was denied by
	// policy.
	ExplainPolicyDenial(ctx context.Context, in *ExplainPolicyDenialRequest, opts ...grpc.CallOption) (*ExplainPolicyDenialResponse, error)
	// RecommendPolicyPatch suggests a policy patch based on a desired behavior
	// description.
	RecommendPolicyPatch(ctx context.Context, in *RecommendPolicyPatchRequest, opts ...grpc.CallOption) (*RecommendPolicyPatchResponse, error)
	// GetRunTimeline returns a chronological timeline of events for a run.
	GetRunTimeline(ctx context.Context, in *GetRunTimelineRequest, opts ...grpc.CallOption) (*GetRunTimelineResponse, error)
	// NextAction recommends the next action based on the current context.
	NextAction(ctx context.Context, in *NextActionRequest, opts ...grpc.CallOption) (*NextActionResponse, error)
	// CronAdd creates a new cron schedule that auto-invokes an agent.
	CronAdd(ctx context.Context, in *CronAddRequest, opts ...grpc.CallOption) (*CronAddResponse, error)
	// CronList lists all cron schedules.
	CronList(ctx context.Context, in *CronListRequest, opts ...grpc.CallOption) (*CronListResponse, error)
	// CronRemove removes a cron schedule.
	CronRemove(ctx context.Context, in *CronRemoveRequest, opts ...grpc.CallOption) (*CronRemoveResponse, error)
	// ListRuns returns all currently tracked agent runs.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Pack(ctx context.Context, in *PackRequest, opts ...grpc.CallOption) (*PackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackResponse)
	err := c.cc.Invoke(ctx, ControlService_Pack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ExportPreview(ctx context.Context, in *ExportPreviewRequest, opts ...grpc.CallOption) (*ExportPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPreviewResponse)
	err := c.cc.Invoke(ctx, ControlService_ExportPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ControlService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, ControlService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, ControlService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_LogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *controlServiceClient) PolicyApply(ctx context.Context, in *PolicyApplyRequest, opts ...grpc.CallOption) (*PolicyApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyApplyResponse)
	err := c.cc.Invoke(ctx, ControlService_PolicyApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SecretSet(ctx context.Context, in *SecretSetRequest, opts ...grpc.CallOption) (*SecretSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretSetResponse)
	err := c.cc.Invoke(ctx, ControlService_SecretSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SecretGrant(ctx context.Context, in *SecretGrantRequest, opts ...grpc.CallOption) (*SecretGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretGrantResponse)
	err := c.cc.Invoke(ctx, ControlService_SecretGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SecretRevoke(ctx context.Context, in *SecretRevokeRequest, opts ...grpc.CallOption) (*SecretRevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretRevokeResponse)
	err := c.cc.Invoke(ctx, ControlService_SecretRevoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AuditQuery(ctx context.Context, in *AuditQueryRequest, opts ...grpc.CallOption) (*AuditQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditQueryResponse)
	err := c.cc.Invoke(ctx, ControlService_AuditQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AuditExport(ctx context.Context, in *AuditExportRequest, opts ...grpc.CallOption) (*AuditExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditExportResponse)
	err := c.cc.Invoke(ctx, ControlService_AuditExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Doctor(ctx context.Context, in *DoctorRequest, opts ...grpc.CallOption) (*DoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorResponse)
	err := c.cc.Invoke(ctx, ControlService_Doctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ValidateAgentProject(ctx context.Context, in *ValidateAgentProjectRequest, opts ...grpc.CallOption) (*ValidateAgentProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAgentProjectResponse)
	err := c.cc.Invoke(ctx, ControlService_ValidateAgentProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SummarizeRun(ctx context.Context, in *SummarizeRunRequest, opts ...grpc.CallOption) (*SummarizeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeRunResponse)
	err := c.cc.Invoke(ctx, ControlService_SummarizeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ExplainFailure(ctx context.Context, in *ExplainFailureRequest, opts ...grpc.CallOption) (*ExplainFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainFailureResponse)
	err := c.cc.Invoke(ctx, ControlService_ExplainFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ExplainPolicyDenial(ctx context.Context, in *ExplainPolicyDenialRequest, opts ...grpc.CallOption) (*ExplainPolicyDenialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainPolicyDenialResponse)
	err := c.cc.Invoke(ctx, ControlService_ExplainPolicyDenial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RecommendPolicyPatch(ctx context.Context, in *RecommendPolicyPatchRequest, opts ...grpc.CallOption) (*RecommendPolicyPatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendPolicyPatchResponse)
	err := c.cc.Invoke(ctx, ControlService_RecommendPolicyPatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetRunTimeline(ctx context.Context, in *GetRunTimelineRequest, opts ...grpc.CallOption) (*GetRunTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunTimelineResponse)
	err := c.cc.Invoke(ctx, ControlService_GetRunTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) NextAction(ctx context.Context, in *NextActionRequest, opts ...grpc.CallOption) (*NextActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextActionResponse)
	err := c.cc.Invoke(ctx, ControlService_NextAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CronAdd(ctx context.Context, in *CronAddRequest, opts ...grpc.CallOption) (*CronAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronAddResponse)
	err := c.cc.Invoke(ctx, ControlService_CronAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CronList(ctx context.Context, in *CronListRequest, opts ...grpc.CallOption) (*CronListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronListResponse)
	err := c.cc.Invoke(ctx, ControlService_CronList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CronRemove(ctx context.Context, in *CronRemoveRequest, opts ...grpc.CallOption) (*CronRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronRemoveResponse)
	err := c.cc.Invoke(ctx, ControlService_CronRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
//
// ControlService provides operational control over agent lifecycle, policy,
// secrets, audit logs, and diagnostic/introspection capabilities.
type ControlServiceServer interface {
	// Pack builds an agent image from a project directory.
	Pack(context.Context, *PackRequest) (*PackResponse, error)
	// ExportPreview returns the export file manifest after preconditions pass.
	ExportPreview(context.Context, *ExportPreviewRequest) (*ExportPreviewResponse, error)
	// Export writes a signed .agentpaas bundle after the secret gate passes.
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	// Run starts a new agent run with the given budget and payload.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Stop terminates a running agent run.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Logs returns a stream of log entries, optionally following in real-time.
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// PolicyApply applies or validates an OPA/Rego policy.
	PolicyApply(context.Context, *PolicyApplyRequest) (*PolicyApplyResponse, error)
	// SecretSet creates or updates a secret.
	SecretSet(context.Context, *SecretSetRequest) (*SecretSetResponse, error)
	// SecretGrant grants a secret to a specific run.
	SecretGrant(context.Context, *SecretGrantRequest) (*SecretGrantResponse, error)
	// SecretRevoke revokes a secret from a specific run.
	SecretRevoke(context.Context, *SecretRevokeRequest) (*SecretRevokeResponse, error)
	// AuditQuery queries audit log entries with filters and pagination.
	AuditQuery(context.Context, *AuditQueryRequest) (*AuditQueryResponse, error)
	// AuditExport exports audit log entries in a specified format.
	AuditExport(context.Context, *AuditExportRequest) (*AuditExportResponse, error)
	// Doctor runs system diagnostics and returns health check results.
	Doctor(context.Context, *DoctorRequest) (*DoctorResponse, error)
	// ValidateAgentProject validates an agent project directory structure and
	// configuration.
	ValidateAgentProject(context.Context, *ValidateAgentProjectRequest) (*ValidateAgentProjectResponse, error)
	// SummarizeRun generates a natural-language summary of a completed run.
	SummarizeRun(context.Context, *SummarizeRunRequest) (*SummarizeRunResponse, error)
	// ExplainFailure analyzes a failed run and returns root cause and suggested
	// fixes.
	ExplainFailure(context.Context, *ExplainFailureRequest) (*ExplainFailureResponse, error)
	// ExplainPolicyDenial explains why a specific destination was denied by
	// policy.
	ExplainPolicyDenial(context.Context, *ExplainPolicyDenialRequest) (*ExplainPolicyDenialResponse, error)
	// RecommendPolicyPatch suggests a policy patch based on a desired behavior
	// description.
	RecommendPolicyPatch(context.Context, *RecommendPolicyPatchRequest) (*RecommendPolicyPatchResponse, error)
	// GetRunTimeline returns a chronological timeline of events for a run.
	GetRunTimeline(context.Context, *GetRunTimelineRequest) (*GetRunTimelineResponse, error)
	// NextAction recommends the next action based on the current context.
	NextAction(context.Context, *NextActionRequest) (*NextActionResponse, error)
	// CronAdd creates a new cron schedule that auto-invokes an agent.
	CronAdd(context.Context, *CronAddRequest) (*CronAddResponse, error)
	// CronList lists all cron schedules.
	CronList(context.Context, *CronListRequest) (*CronListResponse, error)
	// CronRemove removes a cron schedule.
	CronRemove(context.Context, *CronRemoveRequest) (*CronRemoveResponse, error)
	// ListRuns returns all currently tracked agent runs.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) Pack(context.Context, *PackRequest) (*PackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pack not implemented")
}
func (UnimplementedControlServiceServer) ExportPreview(context.Context, *ExportPreviewRequest) (*ExportPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPreview not implemented")
}
func (UnimplementedControlServiceServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedControlServiceServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedControlServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedControlServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedControlServiceServer) PolicyApply(context.Context, *PolicyApplyRequest) (*PolicyApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PolicyApply not implemented")
}
func (UnimplementedControlServiceServer) SecretSet(context.Context, *SecretSetRequest) (*SecretSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretSet not implemented")
}
func (UnimplementedControlServiceServer) SecretGrant(context.Context, *SecretGrantRequest) (*SecretGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretGrant not implemented")
}
func (UnimplementedControlServiceServer) SecretRevoke(context.Context, *SecretRevokeRequest) (*SecretRevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SecretRevoke not implemented")
}
func (UnimplementedControlServiceServer) AuditQuery(context.Context, *AuditQueryRequest) (*AuditQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditQuery not implemented")
}
func (UnimplementedControlServiceServer) AuditExport(context.Context, *AuditExportRequest) (*AuditExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditExport not implemented")
}
func (UnimplementedControlServiceServer) Doctor(context.Context, *DoctorRequest) (*DoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Doctor not implemented")
}
func (UnimplementedControlServiceServer) ValidateAgentProject(context.Context, *ValidateAgentProjectRequest) (*ValidateAgentProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAgentProject not implemented")
}
func (UnimplementedControlServiceServer) SummarizeRun(context.Context, *SummarizeRunRequest) (*SummarizeRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeRun not implemented")
}
func (UnimplementedControlServiceServer) ExplainFailure(context.Context, *ExplainFailureRequest) (*ExplainFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainFailure not implemented")
}
func (UnimplementedControlServiceServer) ExplainPolicyDenial(context.Context, *ExplainPolicyDenialRequest) (*ExplainPolicyDenialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainPolicyDenial not implemented")
}
func (UnimplementedControlServiceServer) RecommendPolicyPatch(context.Context, *RecommendPolicyPatchRequest) (*RecommendPolicyPatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendPolicyPatch not implemented")
}
func (UnimplementedControlServiceServer) GetRunTimeline(context.Context, *GetRunTimelineRequest) (*GetRunTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunTimeline not implemented")
}
func (UnimplementedControlServiceServer) NextAction(context.Context, *NextActionRequest) (*NextActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NextAction not implemented")
}
func (UnimplementedControlServiceServer) CronAdd(context.Context, *CronAddRequest) (*CronAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronAdd not implemented")
}
func (UnimplementedControlServiceServer) CronList(context.Context, *CronListRequest) (*CronListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronList not implemented")
}
func (UnimplementedControlServiceServer) CronRemove(context.Context, *CronRemoveRequest) (*CronRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronRemove not implemented")
}
func (UnimplementedControlServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_Pack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Pack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Pack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Pack(ctx, req.(*PackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ExportPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ExportPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ExportPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ExportPreview(ctx, req.(*ExportPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_LogsServer = grpc.ServerStreamingServer[LogEntry]

func _ControlService_PolicyApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PolicyApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_PolicyApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PolicyApply(ctx, req.(*PolicyApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SecretSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SecretSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SecretSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SecretSet(ctx, req.(*SecretSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SecretGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SecretGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SecretGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SecretGrant(ctx, req.(*SecretGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SecretRevoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SecretRevoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SecretRevoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SecretRevoke(ctx, req.(*SecretRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AuditQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AuditQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AuditQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AuditQuery(ctx, req.(*AuditQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AuditExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AuditExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AuditExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AuditExport(ctx, req.(*AuditExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Doctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Doctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Doctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Doctor(ctx, req.(*DoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ValidateAgentProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAgentProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ValidateAgentProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ValidateAgentProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ValidateAgentProject(ctx, req.(*ValidateAgentProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SummarizeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SummarizeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SummarizeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SummarizeRun(ctx, req.(*SummarizeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ExplainFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ExplainFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ExplainFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ExplainFailure(ctx, req.(*ExplainFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ExplainPolicyDenial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainPolicyDenialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ExplainPolicyDenial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ExplainPolicyDenial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ExplainPolicyDenial(ctx, req.(*ExplainPolicyDenialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RecommendPolicyPatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendPolicyPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RecommendPolicyPatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RecommendPolicyPatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RecommendPolicyPatch(ctx, req.(*RecommendPolicyPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetRunTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetRunTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetRunTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetRunTimeline(ctx, req.(*GetRunTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_NextAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).NextAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_NextAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).NextAction(ctx, req.(*NextActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CronAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CronAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CronAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CronAdd(ctx, req.(*CronAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CronList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CronList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CronList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CronList(ctx, req.(*CronListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CronRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CronRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CronRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CronRemove(ctx, req.(*CronRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentpaas.control.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pack",
			Handler:    _ControlService_Pack_Handler,
		},
		{
			MethodName: "ExportPreview",
			Handler:    _ControlService_ExportPreview_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _ControlService_Export_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _ControlService_Run_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ControlService_Stop_Handler,
		},
		{
			MethodName: "PolicyApply",
			Handler:    _ControlService_PolicyApply_Handler,
		},
		{
			MethodName: "SecretSet",
			Handler:    _ControlService_SecretSet_Handler,
		},
		{
			MethodName: "SecretGrant",
			Handler:    _ControlService_SecretGrant_Handler,
		},
		{
			MethodName: "SecretRevoke",
			Handler:    _ControlService_SecretRevoke_Handler,
		},
		{
			MethodName: "AuditQuery",
			Handler:    _ControlService_AuditQuery_Handler,
		},
		{
			MethodName: "AuditExport",
			Handler:    _ControlService_AuditExport_Handler,
		},
		{
			MethodName: "Doctor",
			Handler:    _ControlService_Doctor_Handler,
		},
		{
			MethodName: "ValidateAgentProject",
			Handler:    _ControlService_ValidateAgentProject_Handler,
		},
		{
			MethodName: "SummarizeRun",
			Handler:    _ControlService_SummarizeRun_Handler,
		},
		{
			MethodName: "ExplainFailure",
			Handler:    _ControlService_ExplainFailure_Handler,
		},
		{
			MethodName: "ExplainPolicyDenial",
			Handler:    _ControlService_ExplainPolicyDenial_Handler,
		},
		{
			MethodName: "RecommendPolicyPatch",
			Handler:    _ControlService_RecommendPolicyPatch_Handler,
		},
		{
			MethodName: "GetRunTimeline",
			Handler:    _ControlService_GetRunTimeline_Handler,
		},
		{
			MethodName: "NextAction",
			Handler:    _ControlService_NextAction_Handler,
		},
		{
			MethodName: "CronAdd",
			Handler:    _ControlService_CronAdd_Handler,
		},
		{
			MethodName: "CronList",
			Handler:    _ControlService_CronList_Handler,
		},
		{
			MethodName: "CronRemove",
			Handler:    _ControlService_CronRemove_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _ControlService_ListRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _ControlService_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/v1/control.proto",
}
