#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Count merged PRs
MERGED_PRS=$(gh pr list --repo parvezsyed/agentpaas --state merged --limit 100 --json number 2>/dev/null | grep -c '"number"' || echo "0")
OPEN_PRS=$(gh pr list --repo parvezsyed/agentpaas --state open --limit 100 --json number 2>/dev/null | grep -c '"number"' || echo "0")

# Determine current block (check which gates pass)
CURRENT_BLOCK="1"
for i in $(seq 1 15); do
    if make block${i}-gate >/dev/null 2>&1; then
        CURRENT_BLOCK=$((i + 1))
    fi
done

cat > docs/status.md << EOF
# AgentPaaS Build Status

**Last Updated:** $TIMESTAMP
**Current Block:** Block $CURRENT_BLOCK

## Block Progress

| Block | Gate | Status |
|-------|------|--------|
| 1 | make block1-gate | Check with \`make block1-gate\` |
| 2-15 | make blockN-gate | Not implemented |

## PR Summary
- Merged PRs: $MERGED_PRS
- Open PRs: $OPEN_PRS

## Recent Commits
$(git log --oneline -10 | sed 's/^/| /')

---
_Generated by scripts/update-status-dashboard.sh_
EOF

echo "Status dashboard updated: docs/status.md"